/**
 * @boina/db — PostgreSQL enum definitions (Drizzle pgEnum)
 *
 * Source: contracts/enums.ts (Zod schemas)
 * All enums are sourced from @boina/contracts for type consistency.
 */

import { pgEnum } from "drizzle-orm/pg-core";

// ─── Account & Business ───────────────────────────────────────────────────────

export const planEnum = pgEnum("plan", ["free", "basic", "pro", "business"]);

// ─── Diagnosis Report ─────────────────────────────────────────────────────────

/**
 * Diagnosis status from contracts/enums.ts ReportStatus
 */
export const diagnosisStatusEnum = pgEnum("diagnosis_status", [
  "queued",
  "running",
  "completed",
  "failed",
  "partial",
  "canceled",
  "timeout",
]);

/**
 * Crawl failure reason from contracts/enums.ts CrawlFailureReason
 */
export const crawlFailureReasonEnum = pgEnum("crawl_failure_reason", [
  "DNS_FAILED",
  "CONNECTION_REFUSED",
  "HTTP_5xx",
  "HTTP_4xx",
  "ROBOTS_BLOCK_ALL",
  "TIMEOUT",
  "JS_RENDER_FAILED",
]);

// ─── Engine Result ────────────────────────────────────────────────────────────

/**
 * Category from contracts/enums.ts
 */
export const categoryEnum = pgEnum("category", ["seo", "aeo", "geo", "a11y", "backlink", "perf"]);

/**
 * ActionType from contracts/enums.ts
 */
export const actionTypeEnum = pgEnum("action_type", [
  "self_fix",
  "snippet_action",
  "vendor_action",
  "si_action",
]);

/**
 * Priority from contracts/enums.ts
 */
export const priorityEnum = pgEnum("priority", ["high", "medium", "low"]);

/**
 * Difficulty from contracts/enums.ts
 */
export const difficultyEnum = pgEnum("difficulty", ["easy", "medium", "hard"]);

/**
 * Impact from contracts/enums.ts
 */
export const impactEnum = pgEnum("impact", ["low", "medium", "high"]);

// ─── Generated Asset (Snippet) ────────────────────────────────────────────────

/**
 * SnippetType from contracts/enums.ts
 */
export const generatedAssetTypeEnum = pgEnum("generated_asset_type", [
  "LOCAL_BUSINESS",
  "ORGANIZATION",
  "SERVICE",
  "FAQ_SCHEMA",
  "BREADCRUMB",
  "LLMS_TXT",
  "FAQ_HTML",
]);

/**
 * Code format (JSON-LD, HTML, etc.)
 */
export const codeFormatEnum = pgEnum("code_format", ["json-ld", "html", "text", "other"]);

/**
 * Generated by (rule, AI, or hybrid)
 */
export const generatedByEnum = pgEnum("generated_by", ["rule", "ai", "hybrid"]);

/**
 * Asset status
 */
export const generatedAssetStatusEnum = pgEnum("generated_asset_status", [
  "draft",
  "published",
  "archived",
]);

// ─── Competitor & Gap Row ─────────────────────────────────────────────────────

/**
 * SourceType from contracts/enums.ts — where competitor data originates
 */
export const sourceTypeEnum = pgEnum("source_type", [
  "website",
  "naver_place",
  "naver_blog",
  "instagram",
  "kakao_place",
  "youtube",
  "facebook",
  "other_platform",
]);

/**
 * Competitor source classification
 */
export const competitorSourceEnum = pgEnum("competitor_source", [
  "naver_serp",
  "gpt_grounded",
  "manual",
]);

// ─── Action (from ActionCompletion) ───────────────────────────────────────────

/**
 * Action tier/urgency from diagnosis specs
 */
export const actionTierEnum = pgEnum("action_tier", [
  "high", // 🔴 Red tier — urgent
  "medium", // 🟡 Yellow tier — moderate
  "low", // 🟢 Green tier — optional
  "waiting", // ⏳ Gray tier — pending
]);

/**
 * Gap row action tier — 도메인 GapActionTier(self_fix/snippet/vendor/ongoing) 값.
 *
 * ⚠️ actionTypeEnum(self_fix/snippet_action/vendor_action/si_action)과 값이 달라 재사용 불가.
 * gap_rows 가 영속화→읽기 왕복에서 action 4분류(🟢🟡🔴⏳)를 보존하도록, gap-service 의
 * 도메인 actionTier(GapItem.actionTier)를 그대로 저장/복원하기 위한 전용 enum 이다.
 * (UI 4분류 매핑: self_fix→green_self / snippet→yellow_copy / vendor→red_vendor / ongoing→gray_ongoing.)
 */
export const gapActionTierEnum = pgEnum("gap_action_tier", [
  "self_fix",
  "snippet",
  "vendor",
  "ongoing",
]);

export const radarSubscriptionStatusEnum = pgEnum("radar_subscription_status", [
  "inactive",
  "trialing",
  "active",
  "past_due",
  "paused",
  "canceled",
]);

export const radarScanTriggerEnum = pgEnum("radar_scan_trigger", ["auto", "manual", "preview"]);

export const radarScanStatusEnum = pgEnum("radar_scan_status", [
  "queued",
  "expanding",
  "scoring",
  "probing",
  "done",
  "partial",
  "skipped",
  "failed",
]);

export const radarKeywordVerdictEnum = pgEnum("radar_keyword_verdict", [
  "now",
  "good",
  "normal",
  "watch",
]);

export const radarFeedbackTypeEnum = pgEnum("radar_feedback_type", [
  "used",
  "not_yet",
  "dismissed",
  "irrelevant",
]);
